services:
  api:
    build: .
    environment:
      - CONNECTIONSTRINGS__DEFAULT=server=db;user=root;password=${DB_PASSWORD:-password};database=poing_dev
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5069
    ports: 
      - "${APP_PORT:-5069}:5069"
  

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=poing_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
    